title: FoodAbout
email: foodaboutourselves@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Food About # add your name
author-pic: FoodaboutLogo.png
about-author: It's all about good food. The blog combines our two passions, travelling and eating good food. We are a couple that loves exploring and sharing the hidden culinary gems with friends around the world. The opinions expressed in this blog are purely personal and subjected to our taste and experience.

# Contact links
email: 	mailto:foodaboutourselves@gmail.com?subject=From foodabout github
phone: # Add your Phone number
website: foodabout.github.io
linkedin: # Add your Linkedin handle
github: foodabout # Add your Github handle
twitter:  FoodAbout1
facebook: # Add your Facebook handle
instagram: foodabout1
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: fa # Add your discus identifier

# Tracker
analytics: 125873458-1

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
